### ISSUE TITLE
Is it possible to use this script with current (unreleased) sources?

### ISSUE THREAD

**Issue by buhrmi** [afiskon/install-couchdb#2]
Looks like there is a bug using the released 2.0.0 version that we're running into (https://issues.apache.org/jira/browse/COUCHDB-3203).

I was wandering if it's possible to somehow adjust the script to download & install using the latest sources instead.

**Comment by afiskon** [comment]
@buhrmi I'm afraid I personally don't have much time to maintain these scripts. Pull requests are welcome.
