### ISSUE TITLE
May I ask how can I set a cluster?

### ISSUE THREAD

**Issue by zelongc** [afiskon/install-couchdb#3]
When I tried to set a cluster, should I set the port as 5986 or 5984?
Thanks...

**Comment by afiskon** [comment]
I don't think it matters. Also please address all technical questions regarding CouchDB on StackOverflow or IRC.

**Comment by zelongc** [comment]
Thanks and have a good day  lol

**Comment by afiskon** [comment]
@zelongc I'm sorry if I disappointed you but it's really kind of question that could be easily googled. 

Particularly you can find a step by step example of configuring a cluster in my article http://eax.me/couchdb/ Link to this article is in the description of this repository. The article is in Russian but it mostly contains code snippets and Google Translate should manage. Before writing it I somehow figured out how to configure a cluster, so it surprises me that you didn't manage to figure it out as well.

Anyway in my humble opinion issues on GitHub is definitely not the right place for asking technical questions.

Sorry once again and good luck!

**Comment by zelongc** [comment]
Oh I am so sorry to waste your time..I am new to github and I should have had some basic understanding of a "ISSUE" etc.......So sorry bro.....And, yes I configure my cluster successfully today. Thank you!
