### ISSUE TITLE
Mirror link 404 error

### ISSUE THREAD

**Issue by alexloiko** [afiskon/install-couchdb#4]
Please replace broken mirror link
http://apache-mirror.rbc.ru/pub/apache/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
to actual
http://apache-mirror.rbc.ru/pub/apache/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz

**Comment by afiskon** [comment]
Hello,

Fixed in d49b4b6d. Thanks for the report!

**Comment by alexloiko** [comment]
Nice!
But next calls also needed to change :)

tar -xvzf apache-couchdb-2.0.0.tar.gz
 cd apache-couchdb-2.0.0/

tar -xvzf apache-couchdb-2.1.1.tar.gz
 cd apache-couchdb-2.1.1/

**Comment by afiskon** [comment]
Oops. Fixed as well!
